#!/bin/sh

mkdir -p opk
cp ./stella-od.elf opk/stella-od
cp ./stella.png opk/stella.png
cp ./License.txt opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Stella
Comment=Atari 2600 emulator
Exec=stella-od %f
Icon=stella
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default."$1".desktop

mksquashfs ./opk stella_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
